sonar.projectKey=cv_analyzer_laravel
sonar.organization=BigMushFrog23

# Paths to scan
sonar.sources=app,config,database,routes,resources/views
sonar.php.exclusions=vendor/**,public/**,storage/**

# Encodings
sonar.sourceEncoding=UTF-8